### ISSUE TITLE
the new update

### ISSUE THREAD

**Issue by loserwear** [Kalaborative/survivio-plus#198] opened 2018-12-13 09:49 UTC
when the hack is enabled when i go into a game it just shows me green and i cant do no nothing

**Comment by yarkoval** [comment] 2018-12-13 10:16
Yeah, have same problem. It caused by todays update. Please be patient and just wait.

**Comment by Tarun430** [comment] 2018-12-13 14:31
I have the problem too

**Comment by survivhacker** [comment] 2018-12-13 14:34
Hopefully, this will be fixed its caused by the new update it should be fixed when the update goes away or by the end of the day.

**Comment by survivhacker** [comment] 2018-12-13 19:49
its not fixed

**Closed** 2018-12-13 23:35 UTC
